@"
services:
  - type: web
    name: nsw-suburb-finder-backend
    env: python
    plan: free
    rootDir: web_app
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /api/stats
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
"@ | Out-File -Encoding utf8 render.yaml